
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Sep 15 19:19:23 CEST 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 14;
  public static final int GREATER_OR_EQUAL = 38;
  public static final int CONST = 12;
  public static final int NUMCONST = 49;
  public static final int MINUS_MINUS = 31;
  public static final int NOT_EQUAL_COMPARATION = 36;
  public static final int GREATER = 37;
  public static final int LPAREN = 6;
  public static final int SEMI = 5;
  public static final int CONTINUE = 22;
  public static final int LESS = 39;
  public static final int MINUS = 24;
  public static final int RPAREN = 7;
  public static final int AND = 28;
  public static final int LESS_OR_EQUAL = 40;
  public static final int OR = 29;
  public static final int COMMA = 8;
  public static final int CLASS = 13;
  public static final int DIV = 26;
  public static final int STEPENOVANJE = 46;
  public static final int PLUS = 23;
  public static final int IF = 51;
  public static final int DOT = 32;
  public static final int TARABA = 43;
  public static final int EOF = 0;
  public static final int RETURN = 10;
  public static final int PLUS_PLUS = 30;
  public static final int RBRACKET = 15;
  public static final int EQUAL = 34;
  public static final int NEW = 20;
  public static final int error = 1;
  public static final int MUL = 25;
  public static final int LINE = 44;
  public static final int MOD = 27;
  public static final int IDENT = 50;
  public static final int BREAK = 17;
  public static final int VOID = 11;
  public static final int COMPARE = 48;
  public static final int COLON = 45;
  public static final int FACTORIEL = 41;
  public static final int ELSE = 52;
  public static final int LBRACE = 3;
  public static final int READ = 21;
  public static final int CHARCONST = 53;
  public static final int FINAL = 47;
  public static final int WHILE = 19;
  public static final int RBRACE = 4;
  public static final int BOOLCONST = 54;
  public static final int EXTENDS = 16;
  public static final int PROG = 2;
  public static final int BINARY = 33;
  public static final int AT = 42;
  public static final int EQUAL_COMPARATION = 35;
  public static final int PRINT = 9;
  public static final int DO = 18;
}

